<div class="row content-block ">
  <div class="col-md-6">
    <h1><?php echo $this->_meta->title() ?></h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
  </div>
  <div class="col-md-6">
    <h1>Bootstrap starter awoogadee</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
  </div>
</div>
  