<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->_homepage->filename() ?>"><?php echo $this->_homepage->title() ?></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <?php foreach (array_slice($this->_pagesMeta, 1) as $page): ?>
        <li><a href="<?php echo $page->filename() ?>"><?php echo $page->title() ?></a></li>
        <?php endforeach ?>
      
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>