<div class="content-block">
    <div class="col-md-12">
        <h1><?php echo $page->title() ?></h1>
        <p class="lead">
            <?php echo $this->headlineText()?>
            <br>
            <br>
            <img src="<?php echo $this->headlineImage()?>"
                 alt="<?php echo $page->title() ?> screenshot" class="headline-image">
        </p>
    </div>

    <?php $this->_renderMainContent($page) ?>

    <div class="col-md-12 alert alert-info">
        <p>
            <em>
                Paid downloads from this page are managed
                using <?php echo Link::external('Oronjo', 'http://www.oronjo.com/') ?>. Clicking the ‘buy’ button
                or download link will take you to the Oronjo site, where the software can be bought via Paypal (using a
                credit card or your Paypal account)
            </em>
        </p>
    </div>
</div>
