<div class="row content-block ">
    <div class="col-md-6">
        <h3>Download full version</h3>
        <p>Device Snapshot Manager is distributed as two fully editable Max For Live .amxd files – one MIDI effect
            and one Audio effect.</p>
        <p>It is known to work with Ableton Live 8, but I've not updated for a very loooong time</p>
        <?php echo $this->_download('Download', 'm4l-device-snapshot-manager-v1-1-1.zip') ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
    <div class="col-md-6 no-spill">
        <h3>Watch</h3>
        <iframe width="336" height="252" src="https://www.youtube.com/embed/IIeFszBbUHc" frameborder="0"
                allowfullscreen=""></iframe>
    </div>
</div>
<div class="col-md-12">
    <h3>Version History</h3>
    <h4>1.1.1</h4>
    <ul>
        <li>Fixed bug where snapshots with more than 128 parameters were not fully recalled</li>
        <li>Improved speed of JS-based Live API interactions</li>
    </ul>
    <h4>1.1.0</h4>
    <ul>
        <li> Added ability to name snapshots</li>
    </ul>
</div>
