<div class="content-block">
	<div class="col-md-12">
	    <h1><?php echo $this->_meta->title() ?></h1>
	    <p class="lead">
	    	I've made some software to help me, (and others) make music, principally with <a href="https://cycling74.com/" target="_blank">Max/MSP</a> and <a href="http://www.ableton.com" target="_blank" >Ableton Live</a>. Some of it is available here. Some is free, some costs a small amount.
	    </p>
	</div>

	<div class="row ">
		<div class="col-md-4">
			<div class="software-menu-item">
				<h3><a href="software-m4l-device-snapshot-manager.html">Device Snapshot Manager</a></h3>
				<p>A Max For Live device that adds the ability to store and recall ‘snapshots’ of Ableton Live devices in realtime</p>
			</div>
		</div>
		<div class="col-md-4">
			<div class="software-menu-item">
				<h3>wacNetworkMIDI</h3>
				<p>Transmit MIDI from one computer to others on a local network without dedicated MIDI hardware</p>
			</div>
		</div>
		<div class="col-md-4">
			<div class="software-menu-item">
				<h3>Miniak Patch Editor</h3>
				<p>Patch editor and manager for the Akai Miniak (and the Alesis Micron)</p>
			</div>
		</div>
	</div>
	<div class="row ">
		<div class="col-md-4">
			<div class="software-menu-item">
				<h3>wacNetworkMIDI 2</h3>
				<p>A tool for transmitting MIDI from one computer to others on a local network without dedicated MIDI hardware</p>
			</div>
		</div>
		<div class="col-md-4">
			<div class="software-menu-item">
				<h3>Miniak Patch Editor 2</h3>
				<p>A patch editor and manager for the Akai Miniak (and the Alesis Micron)</p>
			</div>
		</div>
		<div class="col-md-4">
			<div class="software-menu-item">
				<h3>Device Snapshot Manager 2</h3>
				<p>A Max For Live device that adds the ability to store and recall ‘snapshots’ of Ableton Live devices in realtime</p>
			</div>
		</div>
	</div>
</div>