<div class="content-block">
    <div class="col-md-12">
        <h1><?php echo $page->title() ?></h1>
        <p class="lead">
            <?php echo $page->strapline()?>
            <br>
            <br>
            <img src="<?php echo $this->headlineImage()?>"
                 alt="<?php echo $page->title() ?> screenshot" class="headline-image">
        </p>
    </div>

    <?php $this->_renderMainContent($page) ?>

    <div class="col-md-12 alert alert-info">
        <p>
            <em>
                Paid software downloads from ChipPanFire are managed
                via <?php echo Link::external('Oronjo', 'http://www.oronjo.com/') ?>. Clicking a ‘Buy’ button
                will take you to the Oronjo site where the software can be bought via Paypal
            </em>
        </p>
    </div>
</div>
