<div class="content-block">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $page->title() ?></h1>
            <p class="lead"><?php echo $page->strapline() ?></p>
            <p>I wrote a JS wrapper to allow you to use an Ableton Push in a web browser via the Web MIDI API.
                This page uses that wrapper to drive a drum machine. Plug in your Push to enjoy this page to the max!</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-sm-10 col-xs-12">
            <div class="push-wrapper-buttons">
                <div class="push-wrapper-button"><p>q</p></div>
                <div class="push-wrapper-button"><p>w</p></div>
                <div class="push-wrapper-button"><p>e</p></div>
                <div class="push-wrapper-button"><p>r</p></div>
                <div class="push-wrapper-button"><p>t</p></div>
                <div class="push-wrapper-button"><p>y</p></div>
                <div class="push-wrapper-button"><p>u</p></div>
                <div class="push-wrapper-button"><p>i</p></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div id="no-midi-warning" class="col-md-8 col-sm-10 col-xs-12" style="display: none;"><strong>Looks like your browser doesn't support the Web MIDI API. No Push action for you...</strong></div>
    </div>
    <div class="row">
        <div class="col-md-12">
            Keyboard/mouse control
            <ul>
                <li>play samples by clicking the buttons above</li>
                <li>play samples by pressing your q-w-e-r-t-y-u-i keys</li>
            </ul>
            Push control
            <ul>
                <li>play samples using the grid. One column in the grid plays each sample</li>
                <li>pads higher up the grid raise the sample filter frequency</li>
                <li>press the pads harder to play samples louder</li>
                <li>change sample pitch using the encoders</li>
                <li>modulate pitch of all samples using the touchstrip</li>
                <li>turn on/off note repeat for each sample with the select buttons above the grid</li>
                <li>hold down a select button and press the time division buttons to change note repeat interval</li>
                <li>change the BPM with the tempo knob</li>
            </ul>
            <strong><em>This site is only known to work with Push if you are using Chrome on OS X</em></strong>
        </div>
    </div>
</div>
