<div class="row content-block ">
    <div class="col-md-12">
        <h3>Download full version</h3>
        <p>Where Am I is distributed as a free Max For Live Audio effect (the download also includes documentation). The downloaded .amxd file is fully editable and re-usable.</p>
        <!--TODO To be located on my server, not Oronjo-->
        <a href="http://www.oronjo.com/live/next/?fi=80793" target="_blank">
            <button type="submit" class="btn btn btn-primary">Download</button>
        </a>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
</div>
<div class="col-md-12">
    <h3>Version History</h3>
    <h4>1.1.0</h4>
    <ul>
        <li>Device no longer fills Lives undo buffer when observing changes in selected track/device/etc</li>
    </ul>
</div>
