<div class="row content-block ">
    <div class="col-md-12">
        <h3>Download full version</h3>
        <p>Midi Clip Modulo's functionality can be mapped to keyboard/MIDI shortcuts to quickly integrate into your clip editing workflow. The device always makes edits to the currently selected MIDI clip, and all edits are fully undo-able via Lives undo function</p>
        <?php echo new OronjoBuy('Buy ' . $page->title(), 84684) ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
</div>
