<div class="row content-block ">
    <div class="col-md-12">
        <h3>Download full version</h3>
        <p>Where Am I is distributed as a free Max For Live Audio effect (the download also includes documentation). The downloaded .amxd file is fully editable and re-usable.</p>
        <p>It is known to work with Ableton Live 8, but I've not updated for a very loooong time</p>
        <?php echo $this->_download('Download', 'm4l-where-am-i-v1-1-0.zip') ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
</div>
<div class="col-md-12">
    <h3>Version History</h3>
    <h4>1.1.0</h4>
    <ul>
        <li>Device no longer fills Lives undo buffer when observing changes in selected track/device/etc</li>
    </ul>
</div>
