<div class="row content-block ">
    <div class="col-md-6">
        <h3>Buy full version</h3>
        <p>The paid download includes:</p>
        <ul>
            <li>wacNetworkMIDI application</li>
            <li>Documentation for setup and use</li>
            <li>The MaxMSP source code</li>
        </ul>
        <?php echo new OronjoBuy('Buy ' . $page->title() . ' for OS X', 77529) ?>
        <br>
        <br>
        <?php echo new OronjoBuy('Buy ' . $page->title() . ' for Windows', 77532) ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
    <div class="col-md-6">
        <h3>Download free demo version</h3>
        <p>A demo can be downloaded and used for free, but does not allow you to save default settings</p>
        <p>
            <?php echo $this->_download('Download Demo for OS X', 'demos/wac-Network-Midi-Demo-OSX.zip') ?>
            <br>
            <br>
            <?php echo $this->_download('Download Demo for Windows', 'demos/wac-Network-Midi-Demo-WIN.zip') ?>
        </p>
    </div>
</div>
