<div class="row content-block ">
    <div class="col-md-12">
        <h3>Download full version</h3>
        <p>Midi Clip Modulo's functionality can be mapped to keyboard/MIDI shortcuts to quickly integrate into your clip editing workflow. The device always makes edits to the currently selected MIDI clip, and all edits are fully undo-able via Lives undo function</p>
        <a class="btn btn btn-default" href="http://www.oronjo.com/live/next/?fi=84684" target="_blank"><img
            src="http://www.oronjo.com/live/images/image.php?id=84684" border="0" alt=""><br>Buy MIDI Clip Modulo</a>
        <br>
        <br>
        <form action="http://www.chippanfire.com/cpf_media/software/MidiClipModulo.pdf" method="GET">
            <button type="submit" class="btn btn btn-success">Download Documentation</button>
        </form>
    </div>
</div>
