<div class="content-block">
  <h1><?php echo $page->title() ?></h1>
  <p class="lead">
    I'm a little behind the social media revolution - I'm yet to use anything that's made my life better.
    <br>
    That said, you can find me at:
    <br>
    <?php echo Link::external('Github', 'https://github.com/crosslandwa') ?>
    <br>
    <?php echo Link::internal('Send Mail', 'mailto:willycwillydo@gmail.com') ?>
    <br>
  </p>
</div>
