<div class="content-block">
    <div class="col-md-12">
        <h1><?php echo $page->title() ?></h1>
        <p class="lead">
            I've made some software to help me (and others) make music, principally
            with <?php echo Links::$maxMSP ?>
            and <?php echo Links::$abletonLive ?>. Some of it is available here.
            Some is free, some costs a small amount.
        </p>
    </div>

    <?php foreach (array_chunk($this->_linked, 3) as $groupsOfThree): ?>
        <div class="row ">
            <?php foreach ($groupsOfThree as $linkedPage): ?>
            <div class="col-md-4">
                <div class="software-menu-item">
                    <h3><?php echo $linkedPage->href() ?></h3>
                    <p><?php echo $linkedPage->strapline() ?></p>
                </div>
            </div>
            <?php endforeach ?>
        </div>
    <?php endforeach ?>

</div>
