<div class="row content-block ">
    <div class="col-md-6">
        <h3>Buy full version</h3>
        <p>The paid download includes:</p>
        <ul>
            <li>The Miniak Patch Editor application</li>
            <li>A template for controlling Miniak Patch Editor from the popular iDevice software
                <?php echo Link::external('TouchOSC', 'http://hexler.net/software/touchosc') ?>, created by <strong>Adam
                Neddo</strong> (see documentation for contact details). <em>Note the template controls the editor
                software
                (which updates the Miniak in realtime), but not the Miniak directly</em></li>
            <li>Documentation for setup and use</li>
            <li>A folder of example patches</li>
            <li>The <?php echo Links::$maxMSP ?> source code</li>
        </ul>
        <?php echo new OronjoBuy('Buy ' . $page->title() . ' for OS X', 77513) ?>
        <br>
        <br>
        <?php echo new OronjoBuy('Buy ' . $page->title() . ' for Windows', 77512) ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
    <div class="col-md-6">
        <h3>Download free demo version</h3>
        <p>A demo version can be downloaded and used for free, but does not include the following features:</p>
        <ul>
            <li>Patch management</li>
            <li>Patch randomisation</li>
            <li>OSC interfacing</li>
        </ul>
        <p>It can be used as a fully functional patch editor. I recommend trying the demo before purchasing the full
            version of the software to ensure it suits your needs and works with your synthesizer</p>
        <p>
            <?php echo $this->_download('Download Demo for OS X', 'demos/Minaik-Patch-Editor-Demo-OSX.zip') ?>
            <br>
            <br>
            <?php echo $this->_download('Download Demo for Windows', 'demos/Miniak-Patch-Editor-Demo-WIN.zip') ?>
        </p>
    </div>
</div>
<div class="col-md-12">
    <h3>Version History</h3>
    <h4>1.1.0</h4>
    <ul>
        <li> Added an OSC interface, allowing realtime control of Miniak Patch Editor (and the Miniak) from other OSC
            aware applications
        </li>
        <li>Added &#8216;auto patch retrieval mode&#8217; &#8211; Miniak Patch Editor automatically retreives the loaded
            patch from the Miniak to keep the editor and your synth in sync
        </li>
        <li>Bugfix: certain filter types could only have a maximum frequency of 10KHz, instead of the full 20KHz</li>
    </ul>
</div>
