<div class="row content-block ">
    <div class="col-md-4">
        <h3>Buy full version</h3>
        <p>Device Snapshot Manager is distributed as two fully editable Max For Live .amxd files – one MIDI effect
            and one Audio effect. I intend to offer any updates for free</p>
        <?php echo new OronjoBuy('Buy ' . $page->title(), 79382) ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
    <div class="col-md-4 no-spill">
        <h3>Watch</h3>
        <iframe width="336" height="252" src="http://www.youtube.com/embed/IIeFszBbUHc" frameborder="0"
                allowfullscreen=""></iframe>
    </div>
    <div class="col-md-4">
        <h3>Download free demo version</h3>
        <p>A demo can be downloaded and used for free. It is fully functional and editable, but lacks the following
            features:</p>
        <ul>
            <li>Snapshot naming</li>
            <li>Device randomisation function</li>
            <li>Device reset function</li>
        </ul>
        <p><?php echo $this->_download('Download Demo', '79539') ?></p>
    </div>
</div>
<div class="col-md-12">
    <h3>Version History</h3>
    <h4>1.1.1</h4>
    <ul>
        <li>Fixed bug where snapshots with more than 128 parameters were not fully recalled</li>
        <li>Improved speed of JS-based Live API interactions</li>
    </ul>
    <h4>1.1.0</h4>
    <ul>
        <li> Added ability to name snapshots</li>
    </ul>
</div>
