<div class="content-block">
  <h1><?php echo $page->title() ?></h1>
  <p class="lead">
    I'm a little behind the social media revolution - I'm yet to use anything that's made my life better.
    <br>
    That said, you can find me at:
    <br>
    <a href="https://github.com/crosslandwa" target="_blank">Github</a>
    <br>
    <a href="mailto:willycwillydo@gmail.com" target="_top">Send Mail</a>
    <br>
  </p>
</div>
