<div class="row content-block ">
  <div class="col-md-4">
    <h1>Socco Chico</h1>
    <p class="lead">I make some music (sometimes with <a target="_blank" href="https://soundcloud.com/adamparkinson">Adam Parkinson</a>) for the dancefloor</p>
    <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1644437&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
  </div>
  <div class="col-md-4">
    <h1>Kilclinton</h1>
    <p class="lead">The finest and most coherent album I've ever been involved in making...</p>
    <p>Synth jams and drum edits by Brett Lambe and I</p>
    <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/87360&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
  </div>
  <div class="col-md-4">
    <h1>Carson Brent</h1>
    <p class="lead">My wife sings and I play guitar/sing. </p>
    <p>We used to gig around Bristol many moons ago. We've played at friends' weddings (this is fun). One day I plan on making some new recordings...</p>
  </div>
</div>
