<div class="row content-block ">
    <div class="col-md-12">
        <h3>Download full version</h3>
        <p>Midi Clip Modulo's functionality can be mapped to keyboard/MIDI shortcuts to quickly integrate into your clip editing workflow. The device always makes edits to the currently selected MIDI clip, and all edits are fully undo-able via Lives undo function</p>
        <p>It is known to work with Ableton Live 8, but I've not updated for a very loooong time</p>
        <?php echo $this->_download('Download', 'm4l-midi-clip-modulo-v1-0-0.zip') ?>
        <br>
        <br>
        <?php echo $this->_documentation() ?>
    </div>
</div>
