<div class="row content-block ">
    <div class="col-md-6">
        <h3>Buy full version</h3>
        <p>The paid download includes:</p>
        <ul>
            <li>wacNetworkMIDI application</li>
            <li>Documentation for setup and use</li>
            <li>The MaxMSP source code</li>
        </ul>
        <?php echo new OronjoBuy('Buy ' . $page->title() . ' for OS X', 77529) ?>
        <br>
        <br>
        <?php echo new OronjoBuy('Buy ' . $page->title() . ' for Windows', 77532) ?>
    </div>
    <div class="col-md-6">
        <h3>Download free demo version</h3>
        <p>A demo can be downloaded and used for free, but does not allow you to save default settings</p>
        <p>
            <!--TODO Demos to be located on my server, not Oronjo-->
            <a href="http://www.oronjo.com/live/next/?fi=77528" target="_blank">
                <button type="submit" class="btn btn btn-primary">Download Demo for OS X</button>
            </a>
            <br>
            <br>
            <a href="http://www.oronjo.com/live/next/?fi=77533" target="_blank">
                <button type="submit" class="btn btn btn-primary">Download Demo for Windows</button>
            </a>
        </p>
    </div>
</div>
