<div class="row content-block ">
    <div class="col-md-6">
        <h3>Buy full version</h3>
        <p>The paid download includes:</p>
        <ul>
            <li>wacNetworkMIDI application</li>
            <li>Documentation for setup and use</li>
            <li>The MaxMSP source code</li>
        </ul>
        <a class="btn btn btn-default" href="http://www.oronjo.com/live/next/?fi=77529" target="_blank"><img
            src="http://www.oronjo.com/live/images/image.php?id=77529" border="0" alt=""><br>Buy wacNetworkMIDI for OS X</a>
        <br>
        <br>
        <a class="btn btn btn-default" href="http://www.oronjo.com/live/next/?fi=77532" target="_blank"><img
            src="http://www.oronjo.com/live/images/image.php?id=77532" border="0" alt=""><br>Buy wacNetworkMIDI for Windows</a>
    </div>
    <div class="col-md-6">
        <h3>Download free demo version</h3>
        <p>A demo can be downloaded and used for free, but does not allow you to save default settings</p>
        <p>
            <!--TODO Demos to be located on my server, not Oronjo-->
            <a href="http://www.oronjo.com/live/next/?fi=77528" target="_blank">
                <button type="submit" class="btn btn btn-primary">Download Demo for OS X</button>
            </a>
            <br>
            <br>
            <a href="http://www.oronjo.com/live/next/?fi=77533" target="_blank">
                <button type="submit" class="btn btn btn-primary">Download Demo for Windows</button>
            </a>
        </p>
    </div>
</div>