<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->_homepage->filename() ?>"><?php echo $this->_homepage->title() ?></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <?php foreach (array_slice($this->_pages, 1) as $page): ?>
        <li <?php if ($currentPage === $page) echo 'class="active"' ?> ><?php echo $page->href() ?></li>
        <?php endforeach ?>
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Software <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Miniak Patch Editor</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Max For Live</li>
            <li><a href="#">Device Snapshot Manager</a></li>
            <li><a href="#">Midi Clip Modulo</a></li>
            <li><a href="#">Where Am I</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">WacNetworkMIDI</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Misc</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
