
<!DOCTYPE html>
<html lang="en">
  <?php echo $this->_header->render() ?>

  <body>
    <?php echo $this->_renderNavigation() ?>

    <div class="container main-content">
      <?php $this->_renderContent() ?>
    </div><!-- /.container -->

    <footer class="footer">
      <div class="container">
        <p class="text-muted">ChipPanFire 2016. Email: willycwillydo at gmail dot com</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
